import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { ModalProvider } from "@/providers/modal-provider";
import { prisma } from "@/lib/prisma";
import { ToasterProvider } from "@/providers/toast-provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
}); // Mengkonfigurasi font Inter dari Google Fonts

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; // Metadata untuk aplikasi

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          {/* Panggil ToasterProvider untuk menampilkan notification */}
          <ToasterProvider />{" "}
          {/* Panggil ModalProvider. Pengaturan buka/tutup ModalProvider diatur di @/app/(root)/page.tsx */}
          <ModalProvider /> {children} {/* Render children */}
        </body>
      </html>
    </ClerkProvider>
  );
}
